// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgGU4pyjsjmLntZd0U_0uxOxPU_xvD1O8',
    appId: '1:480380822936:web:a8df37a55e5e7330d9f7ed',
    messagingSenderId: '480380822936',
    projectId: 'kcherryecom',
    authDomain: 'kcherryecom.firebaseapp.com',
    storageBucket: 'kcherryecom.firebasestorage.app',
    measurementId: 'G-EGQC3EG9FG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcwyKlStkdeYF-NTPTIPEY3UbR453_DDo',
    appId: '1:480380822936:android:de287397cdaa332bd9f7ed',
    messagingSenderId: '480380822936',
    projectId: 'kcherryecom',
    storageBucket: 'kcherryecom.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABIFu7JXD3LB3Q_bSkZgOJHJhcLVzNUEs',
    appId: '1:480380822936:ios:b32a4cbca7d5f680d9f7ed',
    messagingSenderId: '480380822936',
    projectId: 'kcherryecom',
    storageBucket: 'kcherryecom.firebasestorage.app',
    iosBundleId: 'com.example.kdigitalEcom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABIFu7JXD3LB3Q_bSkZgOJHJhcLVzNUEs',
    appId: '1:480380822936:ios:b32a4cbca7d5f680d9f7ed',
    messagingSenderId: '480380822936',
    projectId: 'kcherryecom',
    storageBucket: 'kcherryecom.firebasestorage.app',
    iosBundleId: 'com.example.kdigitalEcom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgGU4pyjsjmLntZd0U_0uxOxPU_xvD1O8',
    appId: '1:480380822936:web:c2fdaea4a7c2129fd9f7ed',
    messagingSenderId: '480380822936',
    projectId: 'kcherryecom',
    authDomain: 'kcherryecom.firebaseapp.com',
    storageBucket: 'kcherryecom.firebasestorage.app',
    measurementId: 'G-S4H95DFZTF',
  );
}
